[package]
name = "eddn"
version = "0.0.1-dev+alpha"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"

[dependencies]
elite_journal = { git = "https://github.com/ED-NEWP/elite_journal" }
serde = "*"
serde_json = "*"
chrono = "*"
zmq = "0.9"
miniz_oxide = "0.4"
